services:

  mysql:
    image: mysql:8.0
    networks:
      - solve_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=solve

  solve:
    image: downfa11/solve:latest
    networks:
      - solve_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/solve?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - K8S_API_SERVER_URL=https://localhost:6443
      - K8S_TOKEN=bearertoken
      - K8S_CACERT_PATH=path/to/ca-cert.pem
      - KAKAO_CLIENT_ID=
      - KAKAO_CLIENT_SECRET=
      - KAKAO_REDIRECT_URL=http://localhost/kakao/callback
      - NAVER_CLIENT_ID=
      - NAVER_CLIENT_SECRET=
      - NAVER_REDIRECT_URL=naver/callback
      - k8s.ca.path=/default/path/to/ca-file
      - SPRING_JWT_SECRET=your-very-strong-and-secure-key-123456
      - JWT_ACCESS_EXPIRATION=36000000
      - JWT_REFRESH_EXPIRATION=72000000

networks:
  solve_network:
    driver: bridge
